/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-06-10 17:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.vsstor.util.Constants;
import java.sql.Timestamp;
import java.util.Iterator;
import java.util.Map;
import java.text.SimpleDateFormat;
import com.vsstor.pojo.Configuration;
import java.util.List;
import com.vsstor.pojo.User;

public final class process_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.vsstor.util.Constants");
    _jspx_imports_classes.add("com.vsstor.pojo.User");
    _jspx_imports_classes.add("com.vsstor.pojo.Configuration");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   User u1 = (User) session.getAttribute("user");
			if (u1 == null) {
				response.sendRedirect("login.jsp?msg=Session expired. Login again");
			} else {

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>vs-STOR</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/themify-icons/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/selectFX/css/cs-skin-elastic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/jqvmap/dist/jqvmap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Left Panel -->\r\n");
      out.write("\r\n");
      out.write("\t<aside id=\"left-panel\" class=\"left-panel\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-sm navbar-default\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#main-menu\" aria-controls=\"main-menu\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"welcome.jsp\">VS-STOR</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"navbar-brand hidden\" href=\"./\">V</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"main-menu\" class=\"main-menu collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"welcome.jsp\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-icon fa fa-dashboard\"></i>Dashboard\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"menu-title\">Nodes Operations</h3>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.menu-title -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"configuration?requestType=get\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-icon fa fa-cog\"></i>Configuration\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"health\"> <i class=\"menu-icon fa fa-heart\"></i>Health\r\n");
      out.write("\t\t\t\t\t\t\tCheck\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"menu-title\">Storage Operations</h3>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.menu-title -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"upload\"> <i class=\"menu-icon fa fa-upload\"></i>Upload\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"process\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-icon fa fa-arrows-alt\"></i>Process\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    <h3 class=\"menu-title\">Video Streaming</h3><!-- /.menu-title -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li >\r\n");
      out.write("                        <a href=\"control.jsp\"> <i class=\"menu-icon fa fa-camera\"></i>Control</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"menu-title\">Statistics Operations</h3>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.menu-title -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"report\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-icon fa fa-database\"></i>Report\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"menu-title\">Profile Operations</h3>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.menu-title -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"menu-item-has-children dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-icon fa fa-tasks\"></i>");
      out.print(u1.getFname());
      out.write(' ');
      out.print(u1.getLname());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"menu-icon fa fa-user\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"updateprofile.jsp\">Edit Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"menu-icon fa fa-eye\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"changepassword.jsp\">Change Password</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"menu-icon fa fa-user-times\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"account?request_type=deleteprofile\">Delete Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"menu-icon fa fa-hand-o-left\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"account?request_type=logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\t<!-- /#left-panel -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Left Panel -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Right Panel -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"page-header float-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"page-title\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Process</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"content mt-3\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"card\" style='min-height: 600px;'>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body pb-0\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Here, you can perform operations on the data on the Distributed Storage System</h4>\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

						   String msg = request.getParameter("msg");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

						   if (msg != null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alert alert-success alert-dismissable\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Message!</strong>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(msg);
      out.write(".\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

						   }
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t");

							Map<Configuration, Map<String, String>> result = (Map<Configuration, Map<String, String>>) request.getAttribute("result");
							if (result == null || result.size() == 0)
							{
							   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t<h4>No Files found on the Distributed Storage System</h4>\r\n");
      out.write("\t\t\t\t\t\t\t   ");

							}
							else
							{
							   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t");

							   			Iterator<Configuration> it = result.keySet().iterator();
							   			SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy | hh:mm");
							   			while (it.hasNext())
							   			{
							   			   Configuration conf = it.next();
							   			   Map<String, String> files_list = result.get(conf);
							   			   
							   			   Iterator<String> it2 = files_list.keySet().iterator();
							   			   while (it2.hasNext())
							   			   {
							   			      String file_name = it2.next();
							   			      String format = file_name.substring(file_name.lastIndexOf("."), file_name.length());
							   			      String attr = files_list.get(file_name);
							   			      String arr[] = attr.split("<><>");
							   			      Timestamp creation_time = new Timestamp(Long.parseLong(arr[1]));
							   			      
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t<div class='row' >\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-1' style='text-align:right;'>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t");

							   			      			if (format.contains("txt"))
							   			      			{
							   			      				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t\t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-text-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t\t");
	   
							   			      			}
							   			      			else if (format.contains("zip"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-zip-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("mp3"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-audio-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("java") || format.contains("html") || format.contains(".class") || format.contains("jsp") || format.contains("js") || format.contains("css") || format.contains("py") || format.contains("cpp") || format.contains("cs") || format.equals("c") || format.contains("json"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-code-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("xls"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-excel-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("pdf"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-pdf-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("bmp") || format.contains("jpg") || format.contains("jpeg") || format.contains("png") || format.contains("gif") || format.contains("tif"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-image-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("mp4") || format.contains("wmv") || format.contains("mpeg") )
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-video-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("ppt"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-powerpoint-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("doc"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-word-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      			else if (format.contains("pdf"))
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-pdf-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      		
							   			      			else
							   			      			{
							   			      			   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   \t\t<i style='font-size:79px;' class=\"menu-icon fa fa-file-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t   ");

							   			      			}
							   			      		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t</div>\t\t\t\t\t\t\t   \t\t\t      \t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-3'>");
      out.print(file_name );
      out.write("</div>\t\t\t\t\t\t\t   \t\t\t      \t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-1'>");
      out.print(arr[0] );
      out.write(" KB</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-2'>");
      out.print(sdf.format(creation_time));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-2'>");
      out.print(conf.getHost() );
      out.write("</div>\t\t\t\t\t\t\t   \t\t\t      \t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-2'><a href='http://");
      out.print(conf.getHost());
      out.write(':');
      out.print(conf.getPort());
      out.write('/');
      out.print(conf.getContextroot());
      out.print(Constants.API_FILE_DOWNLOAD);
      out.write("?filename=");
      out.print(file_name);
      out.write("'><i class=\"menu-icon fa fa-download\"></i> Download</a></div>\t\t\t\t\t\t\t   \t\t\t      \t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t<div class='col-md-1'>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t<form action='http://");
      out.print(conf.getHost());
      out.write(':');
      out.print(conf.getPort());
      out.write('/');
      out.print(conf.getContextroot());
      out.print(Constants.API_FILE_DELETE);
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t\t<input type=hidden name='filename' value='");
      out.print(file_name);
      out.write("' />\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t\t<input type=submit value='Delete' class='del' />\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t\t</div>\t\t\t\t\t\t\t   \t\t\t      \t\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      \t<hr/>\r\n");
      out.write("\t\t\t\t\t\t\t   \t\t\t      ");

							   			   }
							   			}
							   		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   ");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form id='refreshForm' style='display:none;' action='process'>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=submit value='submit' />\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- .content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /#right-panel -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Right Panel -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"vendors/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"vendors/chart.js/dist/Chart.bundle.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/widgets.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/jqvmap/dist/jquery.vmap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/jqvmap/examples/js/jquery.vmap.sampledata.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tjQuery('.del').click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tjQuery('#refreshForm').submit();\r\n");
      out.write("\t\t\t}, 1000)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t(function($) {\r\n");
      out.write("\t\t\t\t\"use strict\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tjQuery('#vmap').vectorMap({\r\n");
      out.write("\t\t\t\t\tmap : 'world_en',\r\n");
      out.write("\t\t\t\t\tbackgroundColor : null,\r\n");
      out.write("\t\t\t\t\tcolor : '#ffffff',\r\n");
      out.write("\t\t\t\t\thoverOpacity : 0.7,\r\n");
      out.write("\t\t\t\t\tselectedColor : '#1de9b6',\r\n");
      out.write("\t\t\t\t\tenableZoom : true,\r\n");
      out.write("\t\t\t\t\tshowTooltip : true,\r\n");
      out.write("\t\t\t\t\tvalues : sample_data,\r\n");
      out.write("\t\t\t\t\tscaleColors : [ '#1de9b6', '#03a9f5' ],\r\n");
      out.write("\t\t\t\t\tnormalizeFunction : 'polynomial'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t})(jQuery);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");

   }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
